name: Build and Release Magisk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码并初始化子模块
      - name: Checkout code with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive # 初始化所有子模块

      # 设置 Java 环境为 Java 21
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # 安装依赖项
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip curl python3 python3-pip

      # 使用 build.py 配置 NDK
      - name: Configure NDK
        run: |
          chmod +x ./build.py
          ./build.py ndk

      # 编译 Magisk
      - name: Build Magisk
        run: |
          ./build.py all

      # 获取最新的 Release 信息
      - name: Get latest release
        id: get_latest_release
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/releases/latest

      # 上传编译结果到 Release
      - name: Upload Magisk to Latest Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_latest_release.outputs.upload_url }}
          asset_path: ./out/app-debug.apk # 替换为实际生成的文件路径
          asset_name: magisk.apk
          asset_content_type: application/vnd.android.package-archive