name: Build Magisk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码并初始化子模块
      - name: Checkout code with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # 设置 Java 环境为 Java 21
      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # 安装依赖项
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip curl python3 python3-pip

      # 使用 build.py 配置 NDK
      - name: Configure NDK
        run: |
          chmod +x ./build.py
          ./build.py ndk

      # 编译 Magisk
      - name: Build Magisk
        run: |
          ./build.py all